[package]
name = "shackle-compiler"
version = "0.1.0"
authors = ["Jip J. Dekker <jip@dekker.one>"]
license = "MPL-2.0"

edition = "2021"

[dependencies]
log = "0.4.18"
miette = "7.0.0"
rustc-hash = "2.0.0"
salsa = { git = "https://github.com/salsa-rs/salsa", rev = "ab9aa3ac0850cf8e4fd32c393d78de99e3e9a50c" }
shackle-diagnostics = { path = "../shackle-diagnostics" }
shackle-syntax = { path = "../shackle-syntax" }
stacker = "0.1.15"
streaming-iterator = "0.1.9"
thiserror = "2.0.3"
tree-sitter = "0.24.2"
tree-sitter-eprime = { path = "../../parsers/tree-sitter-eprime" }
tree-sitter-minizinc = { path = "../../parsers/tree-sitter-minizinc" }

[dev-dependencies]
expect-test = "1.4.1"
