[package]
authors = {workspace = true}
edition = {workspace = true}
license = {workspace = true}
name = "shackle-cli"
version = "0.1.0"

[[bin]]
name = "shackle"
path = "src/main.rs"

[dependencies]
clap = {version = "4.3.0", features = ["cargo", "derive"]}
env_logger = {workspace = true}
humantime = "2.1.0"
log = {workspace = true}
miette = {workspace = true, features = ["fancy"]}
serde_json = {workspace = true}
shackle = {path = "../shackle"}
shackle-fmt = {path = "../shackle-fmt", features = ["fancy"]}

[dev-dependencies]
tempfile = "3.5.0"
